= Groovy API Overview (gpars 1.2.1)
The Whole GPars Team <gpars-developers@googlegroups.com>
v1.2.1, 2016-01-11
:linkattrs:
:linkcss:
:toc: right
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://gpars.website/[GPars Documentation]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.
:doctitle: API for Groovy Components Used In *GPars*

++++
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
++++

== Overview Summary of Groovy Packages

=== Packages

++++
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#90DDF7" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Packages</B></FONT></TH>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/package-summary.html">groovyx.gpars</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/activeobject/package-summary.html">groovyx.gpars.activeobject</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/actor/package-summary.html">groovyx.gpars.actor</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/actor/impl/package-summary.html">groovyx.gpars.actor.impl</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/agent/package-summary.html">groovyx.gpars.agent</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/csp/package-summary.html">groovyx.gpars.csp</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/csp/plugAndPlay/package-summary.html">groovyx.gpars.csp.plugAndPlay</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/csp/util/package-summary.html">groovyx.gpars.csp.util</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/package-summary.html">groovyx.gpars.dataflow</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/expression/package-summary.html">groovyx.gpars.dataflow.expression</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/impl/package-summary.html">groovyx.gpars.dataflow.impl</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/operator/package-summary.html">groovyx.gpars.dataflow.operator</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/operator/component/package-summary.html">groovyx.gpars.dataflow.operator.component</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/dataflow/stream/package-summary.html">groovyx.gpars.dataflow.stream</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/extra166y/package-summary.html">groovyx.gpars.extra166y</A></B></TD>
<TD>Collections supporting parallel operations.</TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/forkjoin/package-summary.html">groovyx.gpars.forkjoin</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/group/package-summary.html">groovyx.gpars.group</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/memoize/package-summary.html">groovyx.gpars.memoize</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/pa/package-summary.html">groovyx.gpars.pa</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/remote/package-summary.html">groovyx.gpars.remote</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/remote/message/package-summary.html">groovyx.gpars.remote.message</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/remote/netty/package-summary.html">groovyx.gpars.remote.netty</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/scheduler/package-summary.html">groovyx.gpars.scheduler</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/serial/package-summary.html">groovyx.gpars.serial</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/stm/package-summary.html">groovyx.gpars.stm</A></B></TD>
<TD></TD>
</TR>

<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="groovyx/gpars/util/package-summary.html">groovyx.gpars.util</A></B></TD>
<TD></TD>
</TR>

</TABLE>
++++

''''

== Purpose

The *GPars* framework provides straightforward Groovy-based Domain Specific Languages (DSLs) to declare, which parts of the code should be performed in parallel. 
Objects are enhanced with asynchronous methods like eachParallel(), collectParallel() and others, to perform collection-based operations in parallel. 
Also, closures can be turned into their asynchronous variants, which when invoked schedule the original closure for processing in an executor service. 
The library also provides several helper methods for running a set of closures concurrently.

Effective Scala-like actors are ready to make your code leverage an inherently safer way to organize concurrent code by eliminating mutable shared state altogether. 
With actors support you can quickly create several independent Actors, which consume messages passed to them in their own thread and communicate with other actors by sending them messages. 
You then build your solution by combining these actors into a communication network.

The library has four logical parts.

 . Actors provide a Groovy implementation of Scala-like actors, remote actors, Clojure-like agents and a couple of specialized actors like DynamicDispatchActor or Reactor.
 . Dataflow Concurrency (since version 0.8) allows for very natural shared-memory concurrency model, based on single-assignment variables.
 . And CSP implementation is available as well.
 . ThreadPool uses the Java 1.5 built-in support for executor services to enable multi-threaded collection and closure processing.
 . ForkJoinPool uses JSR-166y Parallel Arrays to enable multi-threaded collection processing.

