= GPars - Groovy Parallel Systems
Jon Kerridge <j.kerridge@napier.ac.uk>
v2.0, 2017-02-01
:linkattrs:
:linkcss:
:toc: right
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://gpars.org/[GPars Documentation]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.

== Extending the *Alternative*: A Scaling Device and Queues

Many machines used in automated processes have some means of monitoring their operation, for example, by calculating running averages of specific values and ensuring they stay within a specified range. 
If they go out of range then the machine recalibrates itself. 

In this chapter, we shall build a model of such a device, but without having to interface to a real machine!

''''

=== The Scaling Device Definition

The scaling device reads incoming integers that arrive every second. The device then multiplies the incoming value by its current scaling factor, which it then outputs, together with the original value. 
The scaling factor is doubled at a regular interval, of say, 5 seconds. 

In addition, there is a controlling function that suspends the operation of the scaling device again at regular intervals, of say, 7 seconds to simulate the testing of its operation.  
When it is suspended, the scaling device outputs its current scaling factor to the controller. 

At some time later, the controller, having computed another scaling factor, will inject the new scaling factor into the controller, which resumes its normal mode of operation. 
While the scaling device is suspended by the controller it outputs all input values unscaled.

''''

NOTE: Want to read more of this chapter? link:pdf/C5.pdf[Download this chapter's PDF here.]

''''
