= Java API Overview (gpars 1.2.1)
The Whole GPars Team <gpars-developers@googlegroups.com>
v1.2.1, 2015-12-11
:linkattrs:
:linkcss:
:toc: right
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://www.gpars.org/guide/[GPars Docs]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.
:doctitle: API for Java Components Used In *GPars*

++++
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
++++

== Overview Summary of Java Packages

=== Packages

++++
<table class="overviewSummary" border="0" cellpadding="3" cellspacing="0" summary="Packages table, listing packages, and an explanation">

<tr>
<th class="colFirst" scope="col">Package</th>
<th class="colLast" scope="col">Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/package-summary.html">groovyx.gpars</a></td>
<td class="colLast">
<div class="block">
    This package holds classes for asynchronous collection processing.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/activeobject/package-summary.html">groovyx.gpars.activeobject</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/actor/package-summary.html">groovyx.gpars.actor</a></td>
<td class="colLast">
<div class="block">
    This package holds classes forming the public actor API.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/actor/impl/package-summary.html">groovyx.gpars.actor.impl</a></td>
<td class="colLast">
<div class="block">
    This package holds classes some non-public aspects of actor implementation.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/agent/package-summary.html">groovyx.gpars.agent</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/package-summary.html">groovyx.gpars.dataflow</a></td>
<td class="colLast">
<div class="block">
    This package holds classes for basic dataflow concurrency constructs, like dataflow variables, streams and threads.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/expression/package-summary.html">groovyx.gpars.dataflow.expression</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/impl/package-summary.html">groovyx.gpars.dataflow.impl</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/operator/package-summary.html">groovyx.gpars.dataflow.operator</a></td>
<td class="colLast">
<div class="block">
    This package holds classes representing operators and channels necessary for full dataflow concurrency.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/operator/component/package-summary.html">groovyx.gpars.dataflow.operator.component</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/dataflow/stream/package-summary.html">groovyx.gpars.dataflow.stream</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/extra166y/package-summary.html">groovyx.gpars.extra166y</a></td>
<td class="colLast">
<div class="block">Collections supporting parallel operations.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/forkjoin/package-summary.html">groovyx.gpars.forkjoin</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/group/package-summary.html">groovyx.gpars.group</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/memoize/package-summary.html">groovyx.gpars.memoize</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/pa/package-summary.html">groovyx.gpars.pa</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/remote/package-summary.html">groovyx.gpars.remote</a></td>
<td class="colLast">
<div class="block">
    This package holds classes implementing the remote actors functionality.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/remote/message/package-summary.html">groovyx.gpars.remote.message</a></td>
<td class="colLast">
<div class="block">
    This package holds message classes for the remote actors implementation.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/remote/netty/package-summary.html">groovyx.gpars.remote.netty</a></td>
<td class="colLast">
<div class="block">
    This package holds implementation-specific classes implementing the remote actors functionality on top of Netty.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/scheduler/package-summary.html">groovyx.gpars.scheduler</a></td>
<td class="colLast">
<div class="block">
    This package holds thread pools / schedulers used by actors and dataflow concurrency.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/serial/package-summary.html">groovyx.gpars.serial</a></td>
<td class="colLast">
<div class="block">
    This package holds classes used for actor identification in the network.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="groovyx/gpars/stm/package-summary.html">groovyx.gpars.stm</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="groovyx/gpars/util/package-summary.html">groovyx.gpars.util</a></td>
<td class="colLast">
<div class="block">
    Various utility classes enhancing basic Java concurrency constructs.</div>
</td>
</tr>
</tbody>
</table>
++++

''''

== Purpose

The *GPars* framework provides straightforward Groovy-based Domain Specific Languages (DSLs) to declare, which parts of the code should be performed in parallel. 
Objects are enhanced with asynchronous methods like eachParallel(), collectParallel() and others, to perform collection-based operations in parallel. 
Also, closures can be turned into their asynchronous variants, which when invoked schedule the original closure for processing in an executor service. 
The library also provides several helper methods for running a set of closures concurrently.

Effective Scala-like actors are ready to make your code leverage an inherently safer way to organize concurrent code by eliminating mutable shared state altogether. 
With actors support you can quickly create several independent Actors, which consume messages passed to them in their own thread and communicate with other actors by sending them messages. 
You then build your solution by combining these actors into a communication network.

The library has four logical parts.

 . Actors provide a Groovy implementation of Scala-like actors, remote actors, Clojure-like agents and a couple of specialized actors like DynamicDispatchActor or Reactor.
 . Dataflow Concurrency (since version 0.8) allows for very natural shared-memory concurrency model, based on single-assignment variables.
 . And CSP implementation is available as well.
 . ThreadPool uses the Java 1.5 built-in support for executor services to enable multi-threaded collection and closure processing.
 . ForkJoinPool uses JSR-166y Parallel Arrays to enable multi-threaded collection processing.

