= GPars - Groovy Parallel Systems
The Whole GPars Team <gpars-developers@googlegroups.com>
v2.0, 2017-02-01
:linkattrs:
:linkcss:
:toc: right
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://gpars.org/[GPars Documentation]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.
:doctitle: Download

== Stable Releases

.Download Individual Components
[cols="5*", options="header", width="70", frame="topbot"]
|===
|GPars 1.0.0
|GPars 1.1.0
|GPars 1.2.0
|GPars 1.2.1
|GPars 2.0

m| JDK 1.5 | JDK 1.5-1.6 | JDK 1.7-1.8 | JDK 1.7-1.8 | JDK 1.8
m|link:downloads/gpars-1.0.0/gpars-1.0.0.jar[GPars Jar File]      m|link:downloads/gpars-1.1.0/gpars-1.1.0.jar[GPars Jar File]      m|link:downloads/gpars-1.2.0/gpars-1.2.0.jar[GPars Jar File]      m|link:downloads/gpars-1.2.1/gpars-1.2.1.jar[GPars Jar File] m|link:downloads/gpars-2.0/gpars-2.0.jar[GPars Jar File]
m|link:downloads/gpars-1.0.0/gpars-all-1.0.0.zip[GPars All Jar]   m|link:downloads/gpars-1.1.0/gpars-all-1.1.0.zip[GPars All Jar]   m|link:downloads/gpars-1.2.0/gpars-all-1.2.0.zip[GPars All Jar]   m|link:downloads/gpars-1.2.1/gpars-all-1.2.1.zip[GPars All Jar]  m|link:downloads/gpars-2.0/gpars-all-2.0.zip[GPars All Jar]
m|link:downloads/gpars-1.0.0/gpars-1.0.0-sources.jar[Source Code] m|link:downloads/gpars-1.1.0/gpars-1.1.0-sources.jar[Source Code] m|link:downloads/gpars-1.2.0/gpars-1.2.0-sources.jar[Source Code] m|link:downloads/gpars-1.2.1/gpars-1.2.1-sources.jar[Source Code]  m|link:downloads/gpars-2.0/gpars-2.0-sources.jar[Source Code]
m|link:downloads/gpars-1.0.0/gpars-1.0.0-javadoc.jar[Java Docs]   m|link:downloads/gpars-1.1.0/gpars-1.1.0-javadoc.jar[Java Docs]   m|link:downloads/gpars-1.2.0/gpars-1.2.0-javadoc.jar[Java Docs]   m|link:downloads/gpars-1.2.1/gpars-1.2.1-javadoc.jar[Java Docs]  m|link:downloads/gpars-2.0/gpars-2.0-javadoc.jar[Java Docs]
m|link:downloads/gpars-1.0.0/gpars-mvn-java-demo-1.0.0.zip[Java/Maven Demo] m|link:downloads/gpars-1.1.0/gpars-mvn-java-demo-1.1.0.zip[Java/Maven Demo] m|link:downloads/gpars-1.2.0/gpars-mvn-java-demo-1.2.0.zip[Java/Maven Demo] m|link:downloads/gpars-1.2.1/gpars-mvn-java-demo-1.2.1.zip[Java/Maven Demo]  m|link:downloads/gpars-2.0/gpars-mvn-java-demo-2.0.zip[Java/Maven Demo]
m|link:downloads/gpars-1.0.0/gpars-samples-1.0.0.zip[Samples]     m|link:downloads/gpars-1.1.0/gpars-samples-1.1.0.zip[Samples]     m|link:downloads/gpars-1.2.0/gpars-samples-1.2.0.zip[Samples]     m|link:downloads/gpars-1.2.1/gpars-samples-1.2.1.zip[Samples]  m|link:downloads/gpars-2.0/gpars-samples-2.0.zip[Samples]
m|link:downloads/gpars-1.0.0/gpars-guide-1.0.0.zip[User Guide]    m|link:downloads/gpars-1.1.0/gpars-guide-1.1.0.zip[User Guide]    m|link:downloads/gpars-1.2.0/gpars-guide-1.2.0.zip[User Guide]    m|link:downloads/gpars-1.2.1/gpars-guide-1.2.1.zip[User Guide]    m|link:downloads/gpars-2.0/gpars-guide-2.0.zip[User Guide]
|===

''''

== Snapshot releases

Downloads of the latest build snapshots from our Bamboo site have been suspended, pending new repository provider.

Note, that you need no special download if you use any of the link:Integration.html[Integration] options.
