= GPars - Groovy Parallel Systems
The Whole GPars Team <gpars-developers@googlegroups.com>
v2.0, 2017-02-01
:linkattrs:
:linkcss:
:toc: right
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://gpars.org/[GPars Documentation]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.
:doctitle: GPars History

== 2008

In October 2008, http://www.vaclavpech.eu/index.html[_Vaclav Pech_] started a pet open-source project called http://code.google.com/p/gparallelizer/[GParallelizer] with the intention to build several easy-to-use Groovy-based DSLs. 
These were built around the _Fork/Join_ and the _ParallelArray_ concept implemented as part of *jsr-166y* java concurrency library.  A thin abstraction layer that allowed Groovy closures to run asynchronously was also included. 

From the impressions of *Scala*, the _actors_ abstraction was added shortly after and has gradually evolved from a mere experiment into a usable implementation.

Some time later, inspired by http://jonasboner.com/[_Jonas Boner's_] experiments with dataflow concurrency, the concept of _dataflow variables_, _streams and tasks_ has been included as well as the *Clojure's* _agent_ concept has been implemented.

== 2009 

In September 2009, _Dierk Koenig, Alex Tkachman, Russel Winder_ and _Paul King_ joined the team, when the project moved to Codehaus under a new name -- *GPars*.

In October 2009, the _dataflow abstraction_ had been enhanced with _dataflow operators_ and an initial _Fork/Join_ convenience layer.

Since December 2009, *GPars* has had a link:GPars_Logo.html[logo].

The team made their first release under the new project name in December 2009 when *GPars* 0.9 came out with a fancy *User Guide*.

From the increasing amount of feedback and comments, it become evident that *GPars* had gained some attention. 

*GPars* was presented at several conferences in Europe and North America (e.g. *W-JAX 2009, JAX 2010, Jfokus 2010, GeeCON 2010*). 
You may also check out a more complete list of link:Presentations.html[Presentations] and link:Events.html[Events].

_Jon Kerridge_ from the *University of Kent* joined *GPars* and contributed his http://www.cs.kent.ac.uk/projects/ofa/jcsp/[JCSP] wrapper library, called _Groovy CSP_, to the project code base.

== 2010-2012

*GPars* reached another milestones in May 2010 with the 0.10 release, 0.11 in October 2011, 0.12 in May 2011 and 1.0 in December 2012.

== 2017

The most recent release, 2.0 arrived in Feb., 2017.
