= GPars - Groovy Parallel Systems
The Whole GPars Team <gpars-developers@googlegroups.com>
v1.0, 2015-10-01
:linkattrs:
:linkcss:
:toc: left
:toc-title: Document Index
:icons: font
:source-highlighter: coderay
:docslink: http://www.gpars.org/guide/[GPars Docs]
:description: GPars is a multi-paradigm concurrency framework offering several mutually cooperating high-level concurrency abstractions.
:doctitle: Hackergarten

== What Is It ?

Hackergarten or Hackathon is a common name used for informal hands-on coding gatherings of developers, who want to spend some of their time helping open-source projects move forward.
 
If you're organizing such an event and think about giving it a concurrency focus, we've prepared a list of *GPars* tasks suitable for Hackergarten.

 . Catchy visual demos - +++http://jira.codehaus.org/browse/GPARS-96+++
 . Concurrent Sudoku solver - +++https://jira.codehaus.org/browse/GPARS-202+++
 . Fix User Guide styles - +++http://jira.codehaus.org/browse/GPARS-243+++
 . Screencasts to explain *GPars* use
 . Make additional Groovy collection processing methods parallel - +++https://jira.codehaus.org/browse/GPARS-209+++
 . Benchmarking
 . Experiment with comet in Grails - +++http://jira.codehaus.org/browse/GPARS-147+++
 . Concurrency gotchas - +++http://jira.codehaus.org/browse/GPARS-150+++
 . Tweak CodeNarc rules - +++http://jira.codehaus.org/browse/GPARS-152+++
 . Revisit the codebase and fix CodeNarc-reported issues - +++http://jira.codehaus.org/browse/GPARS-153+++

== Get Ready

You are only a few easy steps away from being able to start:

 . Clone the source repository - _+++git clone git@github.com:GPars/GPars.git+++_
 . Checkout the _master_ branch - _git checkout master_
 . Build the project to make sure everything works for you - _gradlew clean build_
 . Create an IDEA or Eclipse project files through _gradlew idea_ or _gradlew eclipse_ commands
 . Open the project in IDEA or Eclipse

Please refer to link:Developer_Zone.html[Developer Zone] for details on how to open up the project in an IDE.

Feel free to ask on the mailing list for more details on these topics or perhaps you could try grabbing someone from the team to assist your event on-line.
